<TABLE CELLSPACING="0" CELLPADDING="3" WIDTH="100%" BORDER="0" BGCOLOR="#000000">
<TR BGCOLOR="#000000">
<TD ALIGN="center">
<IMG SRC="images/blank.gif" HEIGHT="1" WIDTH="135" BORDER=0 ALT=""><BR>
<SPAN CLASS="titlebar"><FONT COLOR="#ffffff">Development</FONT></SPAN></TD>
</TR>
<TR ALIGN="right" BGCOLOR="#FFCC33"><TD>
<A CLASS="menus" HREF="structure.shtml">Structure</A><BR>
<A TARGET="_new" CLASS="menus" HREF="http://developer.berlios.de/cvs/?group_id=204">CVS</a> &
<A TARGET="_new" CLASS="menus" HREF="http://cvs.berlios.de/cgi-bin/cvsweb.cgi/?cvsroot=els">CVSWeb</a><BR>
<A TARGET="_new" CLASS="menus" HREF="http://developer.berlios.de/mail/?group_id=204">Mailing list</A><BR>
<A TARGET="_new" CLASS="menus" HREF="http://developer.berlios.de/bugs/?group_id=204">Bugs</A><BR>
<A TARGET="_new" CLASS="menus" HREF="http://developer.berlios.de/patch/?group_id=204">Submit patches</A><BR>
</TD>
</TR></TABLE>

