<!-- logo list -->
<TABLE CELLSPACING="0" CELLPADDING="3" WIDTH="100%" BORDER="0" BGCOLOR="#000000">
<TR ALIGN="center" BGCOLOR="#FFCC33"><TD>&nbsp;</TD></TR>
<TR BGCOLOR="#000000"><TD ALIGN="center">
<IMG SRC="/images/blank.gif" HEIGHT="1" WIDTH="135" BORDER=0 ALT="blank.gif"><BR>
<SPAN CLASS="titlebar"><FONT COLOR="#ffffff">Logos</FONT></SPAN></TD>
</TR>
<TR ALIGN="center" BGCOLOR="#FFCC33"><TD>
<a TARGET="_new" HREF="http://developer.berlios.de"><IMG SRC="http://developer.berlios.de/sflogo.php?group_id=204&type=1" BORDER="0" ALT="BerliOS Logo" WIDTH="118" HEIGHT="52"></a><BR>&nbsp;<BR>
<a TARGET="_new" HREF="http://Petition.eurolinux.org"><img SRC="images/Patent_button.gif" BORDER="0" ALT="Software patents considered harmful" WIDTH="88" HEIGHT="36"></a><BR>&nbsp;<BR>
<a TARGET="_new" HREF="http://validator.w3.org/check/referer"><img SRC="images/vh40.png" BORDER="0" ALT="Valid HTML 4.01!" WIDTH="88" HEIGHT="31"></a>
</TD></TR></TABLE>

<!-- end menus -->

</TD>
<TD WIDTH="9" BGCOLOR="#FFFFFF"><IMG SRC="/images/blank.gif" HEIGHT="1" WIDTH="9" BORDER=0 ALT="blank.gif"></TD>

<!-- content -->
<TD WIDTH="99%">
&nbsp;<BR>
&nbsp;
<BR>
