<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
<TITLE><!--#echo var="title"--></TITLE>
<LINK rel="stylesheet" HREF="els.css" type="text/css">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
</HEAD>
<BODY BGCOLOR="#FFFFFF">

<!-- top title table -->
<TABLE WIDTH="100%" BORDER=0 CELLSPACING=0 CELLPADDING=0 BGCOLOR="">
<TR><TD BGCOLOR="#543a48" colspan=4><IMG SRC="images/blank.gif" ALT="" HEIGHT=2 VSPACE=0></TD></TR>
<TR VALIGN="top" BGCOLOR="#FFCC33"><TD>
<A HREF="index.shtml"><IMG SRC="images/els.gif" VSPACE="0" BORDER=0 WIDTH="238" HEIGHT="104" ALT="Easy Linux Server"></A>
</TD>
<TD WIDTH="10" BGCOLOR="#FFCC33"><img SRC="images/blank.gif" ALT="" BORDER=0 HEIGHT=1 WIDTH=10></TD>
<TD WIDTH="99%" ALIGN="center" VALIGN="middle">
<H1><!--#echo var="title"--></H1></TD>
</TR>
<TR><TD BGCOLOR="#543a48" colspan=4><IMG SRC="images/blank.gif" ALT="" HEIGHT=2 VSPACE=0></TD></TR>
</TABLE>

<!-- content table -->
<TABLE WIDTH="100%" CELLSPACING=0 CELLPADDING=0 BORDER=0>
<TR VALIGN="top">
<TD BGCOLOR="#FFCC33">

<!-- menus -->
<TABLE CELLSPACING="0" CELLPADDING="3" WIDTH="100%" BORDER="0" BGCOLOR="#000000">
<TR BGCOLOR="#000000">
<TD ALIGN="center">
<IMG SRC="images/blank.gif" HEIGHT="1" WIDTH="135" BORDER=0 ALT=""><BR>
<SPAN CLASS="titlebar"><FONT COLOR="#ffffff">General</FONT></SPAN></TD>
</TR>
<TR ALIGN="right" BGCOLOR="#FFCC33"><TD>
<A CLASS="menus" HREF="index.shtml">Home</A><BR>
<A CLASS="menus" HREF="news.shtml">News</A><BR>
<A CLASS="menus" HREF="download.shtml">Download</A><BR>
<A CLASS="menus" HREF="http://developer.berlios.de/mail/?group_id=204" TARGET="_new">Mailing list</A><BR>
<A CLASS="menus" HREF="history.shtml">History</a><BR>
</TD>
</TR></TABLE>

<TABLE CELLSPACING="0" CELLPADDING="3" WIDTH="100%" BORDER="0" BGCOLOR="#000000">
<TR BGCOLOR="#000000">
<TD ALIGN="center">
<IMG SRC="images/blank.gif" HEIGHT="1" WIDTH="135" BORDER=0 ALT=""><BR>
<SPAN CLASS="titlebar"><FONT COLOR="#ffffff">Audience</FONT></SPAN></TD>
</TR>
<TR ALIGN="right" BGCOLOR="#FFCC33"><TD>
<A CLASS="menus" HREF="admins.shtml">Admins</A><BR>
<A CLASS="menus" HREF="developers.shtml">Developers</A><BR>
</TD>
</TR></TABLE>
